### ISSUE TITLE
Add an option to memoize #hash

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-equalizer#3]
For objects that are immutable it doesn't make sense to calculate `#hash` every time it's called, it should be possible to extend the API to provide a configuration for memoizing hash, maybe something like this:

``` ruby
class AintChanging
  include Dry::Equalizer(:foo, :bar, immutable: true)
end
```

This would configure the module to define `#hash` method with memoization.

**Comment by no-reply** [comment]
the flag approach seems like it has some pitfalls. such an object is immutable from when? what if `#hash` is called and cached before that point in construction?

i wonder if `#freeze` could be used for this instead, on a per-instance level:

```ruby
class MaybeFrozen
  include Dry::Equalizer(:foo, :bar)

  def hash(*)
    return super unless frozen?

    @equalizer_hash_cache ||= super
  end
end
```

if this seems like a good approach, i could work up a PR.

**Comment by solnic** [comment]
> such an object is immutable from when?

Right from the start, as in, its initialization. I don't think the library should be defensive like you suggested.
